# Generated by Django 3.2.22 on 2023-11-09 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_localizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='id_endereco',
        ),
        migrations.RemoveField(
            model_name='estabelecimento',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='endereco',
            name='id_estabelicimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estabelecimento'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
    ]
